"""Increase the length of the title column

Revision ID: 651d23cb215c
Revises: 3e4596be74fa
Create Date: 2026-01-05 17:57:02.575856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651d23cb215c'
down_revision = '3e4596be74fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
